# Generated by Django 4.2.24 on 2025-09-27 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_cashflowrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Заполняется автоматически, но может быть изменена вручную', verbose_name='Дата создания записи'),
        ),
    ]
