# docker-compose.yml (только web)
version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true